using System;

namespace PbPTweetAggregator.Test
{
	public class TwitterTestResponses
	{
		public static string Response1 = @"[ { ""contributors"" : null,
    ""coordinates"" : null,
    ""created_at"" : ""Thu Sep 26 19:02:42 +0000 2013"",
    ""entities"" : { ""hashtags"" : [  ],
        ""symbols"" : [  ],
        ""urls"" : [ { ""display_url"" : ""blog.twitter.com/2013/rich-phot…"",
              ""expanded_url"" : ""https://blog.twitter.com/2013/rich-photo-experience-now-in-embedded-tweets-3"",
              ""indices"" : [ 80,
                  103
                ],
              ""url"" : ""https://t.co/XdXRudPXH5""
            } ],
        ""user_mentions"" : [  ]
      },
    ""favorite_count"" : 35,
    ""favorited"" : false,
    ""geo"" : null,
    ""id"" : 383305647283924992,
    ""id_str"" : ""383305647283924992"",
    ""in_reply_to_screen_name"" : null,
    ""in_reply_to_status_id"" : null,
    ""in_reply_to_status_id_str"" : null,
    ""in_reply_to_user_id"" : null,
    ""in_reply_to_user_id_str"" : null,
    ""lang"" : ""en"",
    ""place"" : null,
    ""possibly_sensitive"" : false,
    ""retweet_count"" : 64,
    ""retweeted"" : false,
    ""source"" : ""web"",
    ""text"" : ""Today, Twitter is updating embedded Tweets to enable a richer photo experience: https://t.co/XdXRudPXH5"",
    ""truncated"" : false,
    ""user"" : { ""contributors_enabled"" : false,
        ""created_at"" : ""Wed May 23 06:01:13 +0000 2007"",
        ""default_profile"" : false,
        ""default_profile_image"" : false,
        ""description"" : ""The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website."",
        ""entities"" : { ""description"" : { ""urls"" : [  ] },
            ""url"" : { ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                      ""expanded_url"" : ""http://dev.twitter.com"",
                      ""indices"" : [ 0,
                          22
                        ],
                      ""url"" : ""http://t.co/78pYTvWfJd""
                    } ] }
          },
        ""favourites_count"" : 25,
        ""follow_request_sent"" : false,
        ""followers_count"" : 1871045,
        ""following"" : null,
        ""friends_count"" : 37,
        ""geo_enabled"" : true,
        ""id"" : 6253282,
        ""id_str"" : ""6253282"",
        ""is_translator"" : false,
        ""lang"" : ""en"",
        ""listed_count"" : 12040,
        ""location"" : ""San Francisco, CA"",
        ""name"" : ""Twitter API"",
        ""notifications"" : null,
        ""profile_background_color"" : ""C0DEED"",
        ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_tile"" : true,
        ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/6253282/1347394302"",
        ""profile_image_url"" : ""http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_link_color"" : ""0084B4"",
        ""profile_sidebar_border_color"" : ""C0DEED"",
        ""profile_sidebar_fill_color"" : ""DDEEF6"",
        ""profile_text_color"" : ""333333"",
        ""profile_use_background_image"" : true,
        ""protected"" : false,
        ""screen_name"" : ""twitterapi"",
        ""statuses_count"" : 3451,
        ""time_zone"" : ""Pacific Time (US & Canada)"",
        ""url"" : ""http://t.co/78pYTvWfJd"",
        ""utc_offset"" : -25200,
        ""verified"" : true
      }
  },
  { ""contributors"" : null,
    ""coordinates"" : null,
    ""created_at"" : ""Tue Sep 24 17:46:20 +0000 2013"",
    ""entities"" : { ""hashtags"" : [  ],
        ""symbols"" : [  ],
        ""urls"" : [ { ""display_url"" : ""dev.twitter.com/discussions/21…"",
              ""expanded_url"" : ""https://dev.twitter.com/discussions/21526"",
              ""indices"" : [ 88,
                  111
                ],
              ""url"" : ""https://t.co/Tq3eMHP86c""
            } ],
        ""user_mentions"" : [  ]
      },
    ""favorite_count"" : 27,
    ""favorited"" : false,
    ""geo"" : null,
    ""id"" : 382561653713154049,
    ""id_str"" : ""382561653713154049"",
    ""in_reply_to_screen_name"" : null,
    ""in_reply_to_status_id"" : null,
    ""in_reply_to_status_id_str"" : null,
    ""in_reply_to_user_id"" : null,
    ""in_reply_to_user_id_str"" : null,
    ""lang"" : ""en"",
    ""place"" : null,
    ""possibly_sensitive"" : false,
    ""retweet_count"" : 31,
    ""retweeted"" : false,
    ""source"" : ""web"",
    ""text"" : ""For DMs in User and Site Streams, we're phasing out perspectival attributes. Read more: https://t.co/Tq3eMHP86c"",
    ""truncated"" : false,
    ""user"" : { ""contributors_enabled"" : false,
        ""created_at"" : ""Wed May 23 06:01:13 +0000 2007"",
        ""default_profile"" : false,
        ""default_profile_image"" : false,
        ""description"" : ""The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website."",
        ""entities"" : { ""description"" : { ""urls"" : [  ] },
            ""url"" : { ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                      ""expanded_url"" : ""http://dev.twitter.com"",
                      ""indices"" : [ 0,
                          22
                        ],
                      ""url"" : ""http://t.co/78pYTvWfJd""
                    } ] }
          },
        ""favourites_count"" : 25,
        ""follow_request_sent"" : false,
        ""followers_count"" : 1871045,
        ""following"" : null,
        ""friends_count"" : 37,
        ""geo_enabled"" : true,
        ""id"" : 6253282,
        ""id_str"" : ""6253282"",
        ""is_translator"" : false,
        ""lang"" : ""en"",
        ""listed_count"" : 12040,
        ""location"" : ""San Francisco, CA"",
        ""name"" : ""Twitter API"",
        ""notifications"" : null,
        ""profile_background_color"" : ""C0DEED"",
        ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_tile"" : true,
        ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/6253282/1347394302"",
        ""profile_image_url"" : ""http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_link_color"" : ""0084B4"",
        ""profile_sidebar_border_color"" : ""C0DEED"",
        ""profile_sidebar_fill_color"" : ""DDEEF6"",
        ""profile_text_color"" : ""333333"",
        ""profile_use_background_image"" : true,
        ""protected"" : false,
        ""screen_name"" : ""twitterapi"",
        ""statuses_count"" : 3451,
        ""time_zone"" : ""Pacific Time (US & Canada)"",
        ""url"" : ""http://t.co/78pYTvWfJd"",
        ""utc_offset"" : -25200,
        ""verified"" : true
      }
  },
  { ""contributors"" : null,
    ""coordinates"" : null,
    ""created_at"" : ""Mon Sep 23 16:50:24 +0000 2013"",
    ""entities"" : { ""hashtags"" : [  ],
        ""symbols"" : [  ],
        ""urls"" : [  ],
        ""user_mentions"" : [ { ""id"" : 17197528,
              ""id_str"" : ""17197528"",
              ""indices"" : [ 0,
                  11
                ],
              ""name"" : ""Erich Ocean"",
              ""screen_name"" : ""erichocean""
            } ]
      },
    ""favorite_count"" : 0,
    ""favorited"" : false,
    ""geo"" : null,
    ""id"" : 382185189352284160,
    ""id_str"" : ""382185189352284160"",
    ""in_reply_to_screen_name"" : ""erichocean"",
    ""in_reply_to_status_id"" : 382183335155335169,
    ""in_reply_to_status_id_str"" : ""382183335155335169"",
    ""in_reply_to_user_id"" : 17197528,
    ""in_reply_to_user_id_str"" : ""17197528"",
    ""lang"" : ""en"",
    ""place"" : null,
    ""retweet_count"" : 0,
    ""retweeted"" : false,
    ""source"" : ""web"",
    ""text"" : ""@erichocean We're working to resolve this bug. Thanks for noticing!"",
    ""truncated"" : false,
    ""user"" : { ""contributors_enabled"" : false,
        ""created_at"" : ""Wed May 23 06:01:13 +0000 2007"",
        ""default_profile"" : false,
        ""default_profile_image"" : false,
        ""description"" : ""The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website."",
        ""entities"" : { ""description"" : { ""urls"" : [  ] },
            ""url"" : { ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                      ""expanded_url"" : ""http://dev.twitter.com"",
                      ""indices"" : [ 0,
                          22
                        ],
                      ""url"" : ""http://t.co/78pYTvWfJd""
                    } ] }
          },
        ""favourites_count"" : 25,
        ""follow_request_sent"" : false,
        ""followers_count"" : 1871045,
        ""following"" : null,
        ""friends_count"" : 37,
        ""geo_enabled"" : true,
        ""id"" : 6253282,
        ""id_str"" : ""6253282"",
        ""is_translator"" : false,
        ""lang"" : ""en"",
        ""listed_count"" : 12040,
        ""location"" : ""San Francisco, CA"",
        ""name"" : ""Twitter API"",
        ""notifications"" : null,
        ""profile_background_color"" : ""C0DEED"",
        ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_tile"" : true,
        ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/6253282/1347394302"",
        ""profile_image_url"" : ""http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_link_color"" : ""0084B4"",
        ""profile_sidebar_border_color"" : ""C0DEED"",
        ""profile_sidebar_fill_color"" : ""DDEEF6"",
        ""profile_text_color"" : ""333333"",
        ""profile_use_background_image"" : true,
        ""protected"" : false,
        ""screen_name"" : ""twitterapi"",
        ""statuses_count"" : 3451,
        ""time_zone"" : ""Pacific Time (US & Canada)"",
        ""url"" : ""http://t.co/78pYTvWfJd"",
        ""utc_offset"" : -25200,
        ""verified"" : true
      }
  },
  { ""contributors"" : null,
    ""coordinates"" : null,
    ""created_at"" : ""Mon Sep 23 14:14:06 +0000 2013"",
    ""entities"" : { ""hashtags"" : [  ],
        ""symbols"" : [  ],
        ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
              ""expanded_url"" : ""http://dev.twitter.com"",
              ""indices"" : [ 47,
                  69
                ],
              ""url"" : ""http://t.co/78pYTvWfJd""
            } ],
        ""user_mentions"" : [  ]
      },
    ""favorite_count"" : 15,
    ""favorited"" : false,
    ""geo"" : null,
    ""id"" : 382145856851292160,
    ""id_str"" : ""382145856851292160"",
    ""in_reply_to_screen_name"" : null,
    ""in_reply_to_status_id"" : null,
    ""in_reply_to_status_id_str"" : null,
    ""in_reply_to_user_id"" : null,
    ""in_reply_to_user_id_str"" : null,
    ""lang"" : ""en"",
    ""place"" : null,
    ""possibly_sensitive"" : false,
    ""retweet_count"" : 57,
    ""retweeted"" : false,
    ""source"" : ""web"",
    ""text"" : ""Some users are having difficulty logging in to http://t.co/78pYTvWfJd. We are working to resolve the issue."",
    ""truncated"" : false,
    ""user"" : { ""contributors_enabled"" : false,
        ""created_at"" : ""Wed May 23 06:01:13 +0000 2007"",
        ""default_profile"" : false,
        ""default_profile_image"" : false,
        ""description"" : ""The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website."",
        ""entities"" : { ""description"" : { ""urls"" : [  ] },
            ""url"" : { ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                      ""expanded_url"" : ""http://dev.twitter.com"",
                      ""indices"" : [ 0,
                          22
                        ],
                      ""url"" : ""http://t.co/78pYTvWfJd""
                    } ] }
          },
        ""favourites_count"" : 25,
        ""follow_request_sent"" : false,
        ""followers_count"" : 1871045,
        ""following"" : null,
        ""friends_count"" : 37,
        ""geo_enabled"" : true,
        ""id"" : 6253282,
        ""id_str"" : ""6253282"",
        ""is_translator"" : false,
        ""lang"" : ""en"",
        ""listed_count"" : 12040,
        ""location"" : ""San Francisco, CA"",
        ""name"" : ""Twitter API"",
        ""notifications"" : null,
        ""profile_background_color"" : ""C0DEED"",
        ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_tile"" : true,
        ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/6253282/1347394302"",
        ""profile_image_url"" : ""http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_link_color"" : ""0084B4"",
        ""profile_sidebar_border_color"" : ""C0DEED"",
        ""profile_sidebar_fill_color"" : ""DDEEF6"",
        ""profile_text_color"" : ""333333"",
        ""profile_use_background_image"" : true,
        ""protected"" : false,
        ""screen_name"" : ""twitterapi"",
        ""statuses_count"" : 3451,
        ""time_zone"" : ""Pacific Time (US & Canada)"",
        ""url"" : ""http://t.co/78pYTvWfJd"",
        ""utc_offset"" : -25200,
        ""verified"" : true
      }
  },
  { ""contributors"" : null,
    ""coordinates"" : null,
    ""created_at"" : ""Tue Sep 17 17:28:18 +0000 2013"",
    ""entities"" : { ""hashtags"" : [  ],
        ""symbols"" : [  ],
        ""urls"" : [  ],
        ""user_mentions"" : [ { ""id"" : 229523,
              ""id_str"" : ""229523"",
              ""indices"" : [ 3,
                  12
                ],
              ""name"" : ""Jeff Sandquist"",
              ""screen_name"" : ""jeffsand""
            },
            { ""id"" : 783214,
              ""id_str"" : ""783214"",
              ""indices"" : [ 69,
                  77
                ],
              ""name"" : ""Twitter"",
              ""screen_name"" : ""twitter""
            }
          ]
      },
    ""favorite_count"" : 0,
    ""favorited"" : false,
    ""geo"" : null,
    ""id"" : 380020400320557057,
    ""id_str"" : ""380020400320557057"",
    ""in_reply_to_screen_name"" : null,
    ""in_reply_to_status_id"" : null,
    ""in_reply_to_status_id_str"" : null,
    ""in_reply_to_user_id"" : null,
    ""in_reply_to_user_id_str"" : null,
    ""lang"" : ""en"",
    ""place"" : null,
    ""retweet_count"" : 75,
    ""retweeted"" : false,
    ""retweeted_status"" : { ""contributors"" : null,
        ""coordinates"" : null,
        ""created_at"" : ""Tue Sep 17 17:23:36 +0000 2013"",
        ""entities"" : { ""hashtags"" : [  ],
            ""symbols"" : [  ],
            ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                  ""expanded_url"" : ""http://dev.twitter.com"",
                  ""indices"" : [ 116,
                      138
                    ],
                  ""url"" : ""http://t.co/Xq45CZ2ahl""
                } ],
            ""user_mentions"" : [ { ""id"" : 783214,
                  ""id_str"" : ""783214"",
                  ""indices"" : [ 55,
                      63
                    ],
                  ""name"" : ""Twitter"",
                  ""screen_name"" : ""twitter""
                } ]
          },
        ""favorite_count"" : 70,
        ""favorited"" : false,
        ""geo"" : null,
        ""id"" : 380019216671186944,
        ""id_str"" : ""380019216671186944"",
        ""in_reply_to_screen_name"" : null,
        ""in_reply_to_status_id"" : null,
        ""in_reply_to_status_id_str"" : null,
        ""in_reply_to_user_id"" : null,
        ""in_reply_to_user_id_str"" : null,
        ""lang"" : ""en"",
        ""place"" : null,
        ""possibly_sensitive"" : false,
        ""retweet_count"" : 75,
        ""retweeted"" : false,
        ""source"" : ""web"",
        ""text"" : ""Change invigorates the soul. I am joining the flock at @twitter on October 14, as Director of Platform Partnerships http://t.co/Xq45CZ2ahl"",
        ""truncated"" : false,
        ""user"" : { ""contributors_enabled"" : false,
            ""created_at"" : ""Sun Dec 24 21:52:32 +0000 2006"",
            ""default_profile"" : false,
            ""default_profile_image"" : false,
            ""description"" : ""Future Director of Platform Partnerships @Twitter. Past : Senior Director of Developer Relations at Microsoft. Grew up in Saskatchewan! Car nut, foodie & gamer."",
            ""entities"" : { ""description"" : { ""urls"" : [  ] },
                ""url"" : { ""urls"" : [ { ""display_url"" : ""about.me/JeffSandquist"",
                          ""expanded_url"" : ""http://about.me/JeffSandquist"",
                          ""indices"" : [ 0,
                              22
                            ],
                          ""url"" : ""http://t.co/Upc0wMarRI""
                        } ] }
              },
            ""favourites_count"" : 614,
            ""follow_request_sent"" : false,
            ""followers_count"" : 4531,
            ""following"" : null,
            ""friends_count"" : 739,
            ""geo_enabled"" : true,
            ""id"" : 229523,
            ""id_str"" : ""229523"",
            ""is_translator"" : false,
            ""lang"" : ""en"",
            ""listed_count"" : 293,
            ""location"" : ""Redmond, WA"",
            ""name"" : ""Jeff Sandquist"",
            ""notifications"" : null,
            ""profile_background_color"" : ""000000"",
            ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/378800000053787509/56e20a47f29d87d00b43518023709b0d.png"",
            ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/378800000053787509/56e20a47f29d87d00b43518023709b0d.png"",
            ""profile_background_tile"" : true,
            ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/229523/1376766920"",
            ""profile_image_url"" : ""http://a0.twimg.com/profile_images/3226461261/60465eddf158c5326064bc08fec9788e_normal.jpeg"",
            ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/3226461261/60465eddf158c5326064bc08fec9788e_normal.jpeg"",
            ""profile_link_color"" : ""0000FF"",
            ""profile_sidebar_border_color"" : ""FFFFFF"",
            ""profile_sidebar_fill_color"" : ""E0FF92"",
            ""profile_text_color"" : ""000000"",
            ""profile_use_background_image"" : true,
            ""protected"" : false,
            ""screen_name"" : ""jeffsand"",
            ""statuses_count"" : 6454,
            ""time_zone"" : ""Pacific Time (US & Canada)"",
            ""url"" : ""http://t.co/Upc0wMarRI"",
            ""utc_offset"" : -25200,
            ""verified"" : false
          }
      },
    ""source"" : ""web"",
    ""text"" : ""RT @jeffsand: Change invigorates the soul. I am joining the flock at @twitter on October 14, as Director of Platform Partnerships http://t.…"",
    ""truncated"" : false,
    ""user"" : { ""contributors_enabled"" : false,
        ""created_at"" : ""Wed May 23 06:01:13 +0000 2007"",
        ""default_profile"" : false,
        ""default_profile_image"" : false,
        ""description"" : ""The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website."",
        ""entities"" : { ""description"" : { ""urls"" : [  ] },
            ""url"" : { ""urls"" : [ { ""display_url"" : ""dev.twitter.com"",
                      ""expanded_url"" : ""http://dev.twitter.com"",
                      ""indices"" : [ 0,
                          22
                        ],
                      ""url"" : ""http://t.co/78pYTvWfJd""
                    } ] }
          },
        ""favourites_count"" : 25,
        ""follow_request_sent"" : false,
        ""followers_count"" : 1871045,
        ""following"" : null,
        ""friends_count"" : 37,
        ""geo_enabled"" : true,
        ""id"" : 6253282,
        ""id_str"" : ""6253282"",
        ""is_translator"" : false,
        ""lang"" : ""en"",
        ""listed_count"" : 12040,
        ""location"" : ""San Francisco, CA"",
        ""name"" : ""Twitter API"",
        ""notifications"" : null,
        ""profile_background_color"" : ""C0DEED"",
        ""profile_background_image_url"" : ""http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_image_url_https"" : ""https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png"",
        ""profile_background_tile"" : true,
        ""profile_banner_url"" : ""https://pbs.twimg.com/profile_banners/6253282/1347394302"",
        ""profile_image_url"" : ""http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_image_url_https"" : ""https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"",
        ""profile_link_color"" : ""0084B4"",
        ""profile_sidebar_border_color"" : ""C0DEED"",
        ""profile_sidebar_fill_color"" : ""DDEEF6"",
        ""profile_text_color"" : ""333333"",
        ""profile_use_background_image"" : true,
        ""protected"" : false,
        ""screen_name"" : ""twitterapi"",
        ""statuses_count"" : 3451,
        ""time_zone"" : ""Pacific Time (US & Canada)"",
        ""url"" : ""http://t.co/78pYTvWfJd"",
        ""utc_offset"" : -25200,
        ""verified"" : true
      }
  }
]";
	}
}

